export default function PrivacyPolicy() {
  return (
    <main style={{ padding: '40px 32px', maxWidth: '800px', margin: '0 auto', width: '100%' }}>
      <h1 style={{ marginBottom: '24px' }}>Privacy Policy</h1>
      <div style={{ color: 'var(--text-secondary)', lineHeight: 1.6 }}>
        <p style={{ marginBottom: '16px' }}>
          This Privacy Policy details the data collection practices for the Smart Energy Meter academic project. 
          This is an educational prototype, not a commercial service.
        </p>
        <h3 style={{ color: 'var(--text-primary)', marginTop: '24px', marginBottom: '8px' }}>Data Collection</h3>
        <p style={{ marginBottom: '16px' }}>
          We collect authentication data (email addresses via Firebase Auth) and electrical telemetry generated by your registered ESP32 devices (Voltage, Current, Power, Energy). We may also store local network diagnostics (such as Wi-Fi signal strength and device local IP) for troubleshooting purposes.
        </p>
        <h3 style={{ color: 'var(--text-primary)', marginTop: '24px', marginBottom: '8px' }}>Data Usage & Retention</h3>
        <p style={{ marginBottom: '16px' }}>
          Data is used strictly to display historical charts, calculate estimated electricity bills, and trigger remote threshold alerts. Raw electrical data points are aggregated over time to minimize database storage size.
        </p>
      </div>
    </main>
  );
}